/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface OmActionVerification {
  action_id: Int8;
  after_stats: Generated<Json>;
  after_window: string;
  before_stats: Generated<Json>;
  before_window: string;
  ci_high: number | null;
  ci_low: number | null;
  computed_at: Generated<Timestamp>;
  effect: number | null;
  id: Generated<Int8>;
  method: string;
  run_id: Int8;
  verdict: string;
}

export interface OmAiExplanationSetting {
  enabled: boolean;
  site_id: number | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface OmAnalysisRun {
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  requested_by: string;
  scope: Json;
  started_at: Generated<Timestamp>;
  stats: Generated<Json>;
  status: Generated<string>;
}

export interface OmAsset {
  class_key: string;
  code: string;
  commissioned_at: Timestamp | null;
  criticality: Generated<number>;
  id: Generated<number>;
  level: string;
  name: string;
  nameplate: Generated<Json>;
  parent_id: number | null;
  path: string;
  peer_group: string | null;
  site_id: number;
}

export interface OmAssetClass {
  key: string;
  level: string;
  name_ko: string;
  nameplate_schema: Generated<Json>;
  parent_key: string | null;
  safety_event_codes: Generated<string[]>;
}

export interface OmAssetEvent {
  asset_id: number;
  created_by: string | null;
  id: Generated<Int8>;
  kind: string;
  note: string | null;
  resets_baseline: Generated<boolean>;
  ts: Timestamp;
}

export interface OmAuthAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface OmAuthRateLimit {
  count: number;
  id: string;
  key: string;
  lastRequest: Int8;
}

export interface OmAuthSession {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface OmAuthUser {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface OmAuthVerification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface OmDetectorConfig {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string;
  detector_id: string;
  params: Generated<Json>;
  reference_window: string | null;
  scope: string;
  version: number;
}

export interface OmEpisode {
  asset_id: number;
  conditions: Generated<Json>;
  dq: Generated<Json>;
  end_ts: Timestamp;
  extractor_version: string;
  features: Generated<Json>;
  invalid_reason: string | null;
  kind: string;
  run_id: Int8 | null;
  start_ts: Timestamp;
  valid: boolean;
}

export interface OmEventLog {
  ack_note: string | null;
  acked_at: Timestamp | null;
  acked_by: string | null;
  asset_id: number | null;
  code: string;
  gateway_id: number;
  id: Generated<Int8>;
  is_safety: Generated<boolean>;
  received_at: Timestamp | null;
  severity: string;
  site_id: number;
  source_key: string;
  text: string | null;
  ts: Timestamp;
}

export interface OmFinding {
  asset_id: number | null;
  category: string;
  confidence: number;
  created_at: Generated<Timestamp>;
  dedup_key: string;
  detection_count: Generated<number>;
  detector_id: string;
  detector_version: string;
  dismiss_reason: string | null;
  effect: Generated<Json>;
  failure_mode: string;
  first_detected_at: Timestamp;
  id: Generated<Int8>;
  last_detected_at: Timestamp;
  latest_evidence_id: Int8 | null;
  previous_finding_id: Int8 | null;
  severity: number;
  site_id: number;
  status: Generated<string>;
  summary: string;
  suppressed_until: Timestamp | null;
  title: string;
  updated_at: Generated<Timestamp>;
  window_end: Timestamp;
  window_start: Timestamp;
}

export interface OmFindingEvidence {
  computed_at: Generated<Timestamp>;
  finding_id: Int8;
  id: Generated<Int8>;
  input_hash: string;
  run_id: Int8;
  snapshot: Json;
}

export interface OmFindingExplanation {
  created_at: Generated<Timestamp>;
  evidence_id: Int8;
  finding_id: Int8;
  model: string | null;
  prompt_version: string;
  source: string;
  text: Json;
  validation: Json;
}

export interface OmFindingTransition {
  actor: string;
  at: Generated<Timestamp>;
  finding_id: Int8;
  from_status: string | null;
  id: Generated<Int8>;
  note: string | null;
  to_status: string;
}

export interface OmGateway {
  clock_offset_ms: number | null;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  last_seen_at: Timestamp | null;
  last_seq: Int8 | null;
  site_id: number;
  status: Generated<string>;
}

export interface OmGatewayKey {
  created_at: Generated<Timestamp>;
  gateway_id: number;
  key_id: string;
  revoked_at: Timestamp | null;
  secret_enc: Buffer;
}

export interface OmH2Delivery {
  amount_krw: number | null;
  asset_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  delivered_at: Timestamp;
  heel_mass_kg: number | null;
  id: Generated<Int8>;
  mass_kg: number;
  note: string | null;
  purity_pct: number | null;
  site_id: number;
  source: string;
  supplier: string;
  unit_price_krw: number | null;
  vehicle_no: string | null;
}

export interface OmIngestBatch {
  batch_id: string;
  body_gzip: Buffer;
  body_sha256: Buffer;
  gateway_id: number;
  id: Generated<Int8>;
  n_accepted: Generated<number>;
  n_duplicate: Generated<number>;
  n_events: Generated<number>;
  n_rejected: Generated<number>;
  n_samples: Generated<number>;
  n_unmapped: Generated<number>;
  received_at: Generated<Timestamp>;
  sent_at: Timestamp | null;
  seq: Int8 | null;
  skew_ms: number | null;
  status: string;
}

export interface OmKpiDaily {
  calc_version: string;
  day: Timestamp;
  dq_completeness: number | null;
  kpi_key: string;
  n: Generated<number>;
  scope_id: number;
  scope_type: string;
  unit: string;
  value: number | null;
}

export interface OmM1h {
  bucket: Timestamp;
  computed_at: Generated<Timestamp>;
  n: number;
  n_good: number;
  point_id: number;
  v_avg: number | null;
  v_first: number | null;
  v_last: number | null;
  v_max: number | null;
  v_min: number | null;
  v_sum: number | null;
}

export interface OmMaintenanceAction {
  action_type: string;
  asset_id: number;
  created_at: Generated<Timestamp>;
  created_by: string;
  expected_effect: Json | null;
  finding_id: Int8 | null;
  id: Generated<Int8>;
  notes: string | null;
  performed_at: Timestamp;
  performed_by: string | null;
  site_id: number;
  source: string;
}

export interface OmMarketDaily {
  day: Timestamp;
  market_key: string;
  source: string;
  unit: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Numeric;
}

export interface OmMeasurement {
  point_id: number;
  quality: Generated<number>;
  ts: Timestamp;
  value: number | null;
}

export interface OmMetricDef {
  aliases: Generated<Json>;
  expected_max: number | null;
  expected_min: number | null;
  flatline_max_s: number | null;
  hard_max: number | null;
  hard_min: number | null;
  key: string;
  name_ko: string;
  quantity: string;
  rollup: string;
  unit: string;
  value_kind: string;
}

export interface OmPgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface OmPoint {
  asset_id: number;
  created_at: Generated<Timestamp>;
  gateway_id: number;
  id: Generated<number>;
  instrument_tag: string | null;
  metric_key: string;
  period_s: number | null;
  qualifier: Generated<string>;
  scale: Generated<number>;
  source_key: string;
  source_unit: string | null;
  value_offset: Generated<number>;
}

export interface OmReport {
  approved_at: Timestamp | null;
  approved_by: string | null;
  composer_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  draft: Json;
  id: Generated<Int8>;
  pack: Json;
  pack_hash: string;
  period: string;
  site_id: number;
  status: Generated<string>;
  validation: Json;
}

export interface OmRollupDirty {
  bucket: Timestamp;
  gen: Generated<Int8>;
  point_id: number;
  touched_at: Generated<Timestamp>;
}

export interface OmSite {
  attributes: Generated<Json>;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  lat: number | null;
  lon: number | null;
  name: string;
  timezone: Generated<string>;
}

export interface OmSiteEnergyDaily {
  alloc_version: string;
  calc_version: string;
  computed_at: Generated<Timestamp>;
  day: Timestamp;
  dq: Json;
  elz_grid_share: number | null;
  elz_sec_kwh_per_kg: number | null;
  energy_kwh: Json;
  fc_kg_per_mwh: number | null;
  flows_kwh: Json;
  h2_kg: Json;
  p2p_efficiency: number | null;
  pv_loss_kwh: Json | null;
  renewable_share: number | null;
  run_id: Int8;
  site_id: number;
}

export interface OmUnmappedSource {
  first_seen_at: Generated<Timestamp>;
  gateway_id: number;
  last_seen_at: Generated<Timestamp>;
  sample_count: Generated<Int8>;
  source_key: string;
  unit: string | null;
}

export interface SimEvalResult {
  details: Generated<Json>;
  detector_id: string;
  fn: number;
  fp: number;
  fp_per_asset_month: number | null;
  magnitude_mae: number | null;
  median_delay_days: number | null;
  precision: number | null;
  recall: number | null;
  run_id: Int8;
  tp: number;
}

export interface SimInjection {
  asset_path: string | null;
  end_ts: Timestamp | null;
  expected_failure_modes: Generated<string[]>;
  id: Generated<Int8>;
  kind: string;
  params: Generated<Json>;
  run_id: Int8;
  site_code: string;
  start_ts: Timestamp;
}

export interface SimRun {
  config: Json;
  created_at: Generated<Timestamp>;
  engine_version: string;
  id: Generated<Int8>;
  seed: number;
}

export interface DB {
  "om.action_verification": OmActionVerification;
  "om.ai_explanation_setting": OmAiExplanationSetting;
  "om.analysis_run": OmAnalysisRun;
  "om.asset": OmAsset;
  "om.asset_class": OmAssetClass;
  "om.asset_event": OmAssetEvent;
  "om.auth_account": OmAuthAccount;
  "om.auth_rate_limit": OmAuthRateLimit;
  "om.auth_session": OmAuthSession;
  "om.auth_user": OmAuthUser;
  "om.auth_verification": OmAuthVerification;
  "om.detector_config": OmDetectorConfig;
  "om.episode": OmEpisode;
  "om.event_log": OmEventLog;
  "om.finding": OmFinding;
  "om.finding_evidence": OmFindingEvidence;
  "om.finding_explanation": OmFindingExplanation;
  "om.finding_transition": OmFindingTransition;
  "om.gateway": OmGateway;
  "om.gateway_key": OmGatewayKey;
  "om.h2_delivery": OmH2Delivery;
  "om.ingest_batch": OmIngestBatch;
  "om.kpi_daily": OmKpiDaily;
  "om.m_1h": OmM1h;
  "om.maintenance_action": OmMaintenanceAction;
  "om.market_daily": OmMarketDaily;
  "om.measurement": OmMeasurement;
  "om.metric_def": OmMetricDef;
  "om.pgmigrations": OmPgmigrations;
  "om.point": OmPoint;
  "om.report": OmReport;
  "om.rollup_dirty": OmRollupDirty;
  "om.site": OmSite;
  "om.site_energy_daily": OmSiteEnergyDaily;
  "om.unmapped_source": OmUnmappedSource;
  "sim.eval_result": SimEvalResult;
  "sim.injection": SimInjection;
  "sim.run": SimRun;
}
