// 원인 판별 체크 측정값 키 → 표시 이름. 순수 모듈. 키는 lib/analytics/detectors의 checks.measured를 따른다.

const LABELS: Readonly<Record<string, string>> = {
  // ess.capacity_fade
  t_ref_c: '기준 셀온도 (°C)',
  t_recent_c: '최근 셀온도 (°C)',
  shift_c: '온도 변화 (°C)',
  setpoint_changes: '설정 변경 기록 (건)',
  soc_end_ref: '기준 충전 종료 SOC (%)',
  soc_end_recent: '최근 충전 종료 SOC (%)',
  cc_ah_ref: '기준 CC 구간 (Ah)',
  cc_ah_recent: '최근 CC 구간 (Ah)',
  cc_ah_change_pct: 'CC 구간 변화 (%)',
  cv_s_ref: '기준 CV 시간 (s)',
  cv_s_recent: '최근 CV 시간 (s)',
  cv_s_change_pct: 'CV 시간 변화 (%)',
  cell_dv_end_ref_mv: '기준 종료 셀 편차 (mV)',
  cell_dv_end_recent_mv: '최근 종료 셀 편차 (mV)',
  rise_mv: '편차 증가 (mV)',
  firmware_or_calibration_events: '펌웨어·교정 기록 (건)',
  jump_share_ref: '기준 SOC 점프 비율',
  jump_share_recent: '최근 SOC 점프 비율',
  // el.voltage_rise · fc.voltage_decay
  early_c: '초기 운전 온도 (°C)',
  late_c: '최근 운전 온도 (°C)',
  early_kw: '초기 블로워 전력 (kW)',
  late_kw: '최근 블로워 전력 (kW)',
  rise_pct: '블로워 전력 증가 (%)',
  // P3 공통
  n: '표본 수',
  pearson_r: '상관계수 r',
  ref_c: '기준 온도 (°C)',
  recent_c: '최근 온도 (°C)',
  ref_pct: '기준 (%)',
  recent_pct: '최근 (%)',
  change_pct: '변화 (%)',
  days: '일수',
  // tank.static_leak
  offset_slope_bar_per_day: '압력 차이 추세 (bar/일)',
  apparent_loss_kg_per_day: '겉보기 손실 (kg/일)',
  share_of_leak: '누설률 대비 비율',
  sources: '비교 압력',
  holds_with_data: '하류 압력 있는 구간',
  holds_with_rise: '하류 압력 상승 구간',
  recent_holds: '최근 정지 구간',
  target_holds: '목표 구간 수',
  median_hours: '구간 길이 중앙값 (h)',
  min_static_hours: '최소 정지 시간 (h)',
  // h2chain.mass_balance_gap
  ref_ratio_pct: '기준 유량계/패러데이 (%)',
  recent_ratio_pct: '최근 유량계/패러데이 (%)',
  static_leak_status: '누설 판정',
  leak_kg_per_day: '누설률 (kg/일)',
  residual_kg_per_day: '일 잔차 (kg)',
  share: '설명 비율',
  missing_or_low_quality_days: '결측·품질 미달일',
  window_days: '확인 기간 (일)',
  // el.sec_rise
  v_cell_rise_pct: '셀 전압 상승 (%)',
  v_cell_rise_mv: '셀 전압 상승 (mV)',
  share_of_sec_rise: '비에너지 상승 설명 비율',
  ref_share: '기준 부분부하 비중',
  recent_share: '최근 부분부하 비중',
  ref_per_day: '기준 일 퍼지 (회)',
  recent_per_day: '최근 일 퍼지 (회)',
  // comp.sec_rise
  ref_bar: '기준 누설 감지 압력 (bar)',
  recent_bar: '최근 누설 감지 압력 (bar)',
  recent_max_bar: '최근 최고 (bar)',
  // fc.blower_wear
  filter_events: '필터 교체 (날짜 회복 %)',
  ref_mv: '기준 셀 전압 (mV)',
  recent_mv: '최근 셀 전압 (mV)',
  // ess.resistance_growth
  ref_dv_mv: '기준 셀 편차 (mV)',
  recent_dv_mv: '최근 셀 편차 (mV)',
  capacity_effect_pct: '용량 효과 (%)',
  capacity_ci_high_pct: '용량 CI 상한 (%)',
  periods_s: '샘플 주기 (s)',
  used_period_s: '비교 주기 (s)',
  excluded_steps: '뺀 계단 (회)',
  // pv.soiling_rate
  inverters: '인버터 (대)',
  declining: '저하 인버터 (대)',
  rates_pct_per_day: '인버터별 오염 속도',
  ratio_shift_pct: 'GHI/POA 비율 변화 (%)',
  last_year_rate_pct_per_day: '전년 오염 속도 (%/일)',
  last_year_clear_days: '전년 맑은 날',
  reset_kind: '복원 종류',
  recovery_pct: '회복 폭 (%)',
  // inv.thermal_derating
  derate_buckets_below_hot_ambient_share: '고온 외기 미만 저감 비율',
  ref_ambient_max_c: '기준 일 최고 외기 (°C)',
  recent_ambient_max_c: '최근 일 최고 외기 (°C)',
  fan_fault_events: '냉각팬 고장 코드 (건)',
  hot_buckets: '고온 버킷',
  peers_hot_together_share: '동종 동시 고온 비율',
  excluded_limited_buckets: '뺀 출력제한 버킷',
  derate_buckets_with_peer_limit_share: '동종 제한 겹침 비율',
};

export function measuredLabel(key: string): string {
  return LABELS[key] ?? key;
}
